In [ ]:
import sys
# Check Python version
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
  print("Hello, World!")
  print(f"Python version: {sys.version}")
else:
  print("Please use Python 3.6 or higher.")

Hello, World!
Python version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]


In [ ]:
# Mutable Data Type Example (List)
my_list = [1, 2, 3]
print("Original List:", my_list)
# Modifying the list (changing contents)
my_list.append(4)
print("Modified List:", my_list)
# Immutable Data Type Example (Tuple)
my_tuple = (1, 2, 3)
print("Original Tuple:", my_tuple)
# Trying to modify the tuple (will raise an error)
# my_tuple.append(4) # Uncommenting this line will raise an AttributeError

Original List: [1, 2, 3]
Modified List: [1, 2, 3, 4]
Original Tuple: (1, 2, 3)


In [ ]:
# Immutable Data Type Example (Tuple)
my_tuple = (1, 2, 3)
print("Original Tuple:", my_tuple)
# Trying to modify the tuple (will raise an error)
my_tuple.append(4) # Uncommenting this line will raise an AttributeError

Original Tuple: (1, 2, 3)


AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
age = 23 #int
pi = 3.14 #float
temperature = -5.5 #float
print("data type of variable age = ", type(age))
print("data type of variable pi = ", type(pi))
print("data type of variable temperature = ", type(temperature))

data type of variable age =  <class 'int'>
data type of variable pi =  <class 'float'>
data type of variable temperature =  <class 'float'>


In [ ]:
name = "Alice"
greeting = 'Hello'
address = "123 Main St"
print("data type of the variable name = ",type(name))
print("data type of the variable greeting = ",type(greeting))
print("data type of the variable address = ",type(address))
# slice only one element
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])
# slice a range of elements
print("The second letter to the fourth of the name is:", name[1:4])
print("The first two letters of the name are:", name[:2])
print("Substring starting from the third letter is:", name[2:])

data type of the variable name =  <class 'str'>
data type of the variable greeting =  <class 'str'>
data type of the variable address =  <class 'str'>
The first letter of the name is: A
The last letter of the name is: e
The second letter to the fourth of the name is: lic
The first two letters of the name are: Al
Substring starting from the third letter is: ice


In [ ]:
list1 = [1, 2, 3, 4]
mixed_list = [12, "Hello", True]
# List is mutable
mixed_list[0] = False
mixed_list

[False, 'Hello', True]

In [ ]:
colors = ('red', 'green', 'yellow', 'blue')
print("First element:", colors[0])
print("Last two elements:", colors[2:])
print("Middle two elements:", colors[1:3])
colors[0] = 'purple'
colors # will generate an error as tuple is immutable.

First element: red
Last two elements: ('yellow', 'blue')
Middle two elements: ('green', 'yellow')


TypeError: 'tuple' object does not support item assignment

In [ ]:
person = {'name':'John',
          'age':30,
          'city':'Pittsburgh'}
print(f"Hello my name is {person['name']}. I am {person['age']} years old and I live at {person['city']}.")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))

Hello my name is John. I am 30 years old and I live at Pittsburgh.
All keys: ['name', 'age', 'city']
All values: ['John', 30, 'Pittsburgh']


In [ ]:
unique_numbers = {1,2,3,3,3,3,4,5}
print(unique_numbers)

{1, 2, 3, 4, 5}


In [ ]:
set1 = {"apple", "banana", "cherry", "apple",'apple'}
set2 = {1, 5, 7, 9, 3, 1}
set3 = {True, False, False}
print(set1);
print(set2);
print(set3);

{'apple', 'banana', 'cherry'}
{1, 3, 5, 7, 9}
{False, True}


**IF-ELSE**

In [ ]:
x = 5
y = 10
if x > 0 and y < 20:
    print("Both conditions are true")
if x > 0 or y > 20:
  print("At least one condition is true")
if not x == 0:
  print("x is not equal to 0")

Both conditions are true
At least one condition is true
x is not equal to 0


**LOOPS**

In [ ]:
# for loop:
fruits = ["apple", "banana","cherry"]
for fruit in fruits:
  print(fruit)

# While loop:
count = 0
while count < 5:
  print("Count is:", count)
count += 1

# Break
fruits = ["apple", "banana", "orange"]
print("loop 1")
for fruit in fruits:
  print(fruit)
  if fruit == "apple":
   break

# Continiue
print("loop 2")
for fruit in fruits:
 if fruit == "apple":
    continue
else:
  print(fruit)

**Functions**

In [ ]:
def add_binary(a, b):
    """
    Returns the sum of two decimal numbers in binary digits.

    Parameters:
    a (int): A decimal integer
    b (int): Another decimal integer

    Returns:
    binary_sum (str): Binary string of the sum of a and b
    """
    # Sum the integers and convert to binary string using bin()
    # [2:] removes the '0b' prefix that Python adds to binary strings
    binary_sum = bin(a + b)[2:]
    return binary_sum

result = add_binary(5, 3)
print(result)  # Output: '1000'



1000


**Built - in - Functions**

In [ ]:
print("Hello, World!")
length = len("Hello")
print(length)
data_type = type(42)
print(data_type)
total = sum([1, 2, 3])
print(total)

Hello, World!
5
<class 'int'>
6


**Built - in - Methods**

In [ ]:
# str.upper(): Converts all characters in a string to uppercase.
print("hello".upper());
# list.append(): Adds an element to the end of a list.
fruits = ["apple", "banana"]
fruits.append("cherry");
print(fruits)
# dict.get(): Returns the value associated with a key in a dictionary.
info = {"name": "Alice", "age": 25}
print(info.get("age"))# Output: 25

HELLO
['apple', 'banana', 'cherry']
25


**User - Defined - Function**

This function converts temperature between Celsius and Fahrenheit.
This function prompts the user to specify the conversion type (Celsius to Fahrenheit or
Fahrenheit to Celsius)
and then asks for the temperature value. It calculates and returns the converted temperature.
Returns:
float: The converted temperature value.

In [ ]:
def temperature_converter():

  print("Choose conversion type:")
  print("1. Celsius to Fahrenheit")
  print("2. Fahrenheit to Celsius")
  # Get conversion choice from user
  choice = input("Enter 1 or 2: ")
  if choice == "1":
  # Celsius to Fahrenheit conversion
    celsius = float(input("Enter temperature in Celsius: "))
    fahrenheit = (celsius * 9/5) + 32
    print(f"{celsius}C is equal to {fahrenheit}F")
    return fahrenheit
  elif choice == "2":
    # Fahrenheit to Celsius conversion
    fahrenheit = float(input("Enter temperature in Fahrenheit: "))
    celsius = (fahrenheit - 32) * 5/9
    print(f"{fahrenheit}F is equal to {celsius}C")
    return celsius
  else:
    print("Invalid choice. Please enter 1 or 2.")
    return None
# Call the function
temperature_converter()

Choose conversion type:
1. Celsius to Fahrenheit
2. Fahrenheit to Celsius
Enter 1 or 2: 1
Enter temperature in Celsius: 37
37.0C is equal to 98.6F


98.6

**Accessing and Modifying Global Variables Inside a Function**
Using global here allows the function to modify the global variable x directly.

In [ ]:
x = 10 # Global variable
def modify_global():
  global x # Declaring x as global
  x = 20 # Modifying global x
modify_global()
print(x) #

20


**TO-DO-TASKS**

**4.1 Exercise on Functions:**
Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

In [ ]:
def convert_units():
    """
    Converts units of measurement based on user choice.

    The user selects a conversion type (length, weight, or volume),
    inputs a value, and the program converts it accordingly.

    Returns:
        None
    """

    print("Choose conversion type: length, weight, volume")
    conversion_type = input("Enter conversion type: ").lower()

    try:

        # LENGTH
        if conversion_type == "length":
            print("1. Meter (m) to Feet (ft)")
            print("2. Feet (ft) to Meter (m)")
            option = input("Choose 1 or 2: ")

            value = float(input("Enter value: "))

            if option == "1":
                result = value * 3.28084
                print(f"{value} m = {result:.2f} ft")

            elif option == "2":
                result = value / 3.28084
                print(f"{value} ft = {result:.2f} m")

            else:
                print("Invalid option.")


        # WEIGHT
        elif conversion_type == "weight":
            print("1. Kilogram (kg) to Pounds (lbs)")
            print("2. Pounds (lbs) to Kilogram (kg)")
            option = input("Choose 1 or 2: ")

            value = float(input("Enter value: "))

            if option == "1":
                result = value * 2.20462
                print(f"{value} kg = {result:.2f} lbs")

            elif option == "2":
                result = value / 2.20462
                print(f"{value} lbs = {result:.2f} kg")

            else:
                print("Invalid option.")


        # VOLUME
        elif conversion_type == "volume":
            print("1. Liters (L) to Gallons (gal)")
            print("2. Gallons (gal) to Liters (L)")
            option = input("Choose 1 or 2: ")

            value = float(input("Enter value: "))

            if option == "1":
                result = value * 0.264172
                print(f"{value} L = {result:.2f} gal")

            elif option == "2":
                result = value / 0.264172
                print(f"{value} gal = {result:.2f} L")

            else:
                print("Invalid option.")

        else:
            print("Unsupported conversion type.")

    except ValueError:
        print("Invalid input. Please enter a numeric value.")


# Run program
convert_units()

Choose conversion type: length, weight, volume
Enter conversion type: weight
1. Kilogram (kg) to Pounds (lbs)
2. Pounds (lbs) to Kilogram (kg)
Choose 1 or 2: 1
Enter value: 37
37.0 kg = 81.57 lbs


**Task - 2:**
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

In [ ]:
def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The sum of the numbers.
    """
    return sum(numbers)


def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The average of the numbers.
    """
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The maximum number in the list.
    """
    return max(numbers)


def find_min(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The minimum number in the list.
    """
    return min(numbers)


def main():
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter your choice (1-4): ")

    try:
        numbers_input = input("Enter numbers separated by spaces: ")
        numbers = [float(num) for num in numbers_input.split()]

        if len(numbers) == 0:
            raise ValueError("Empty list")

        if choice == "1":
            result = calculate_sum(numbers)
            print("Sum:", result)

        elif choice == "2":
            result = calculate_average(numbers)
            print("Average:", result)

        elif choice == "3":
            result = find_max(numbers)
            print("Maximum:", result)

        elif choice == "4":
            result = find_min(numbers)
            print("Minimum:", result)

        else:
            print("Invalid operation selected.")

    except ValueError:
        print("Invalid input. Please enter numeric values separated by spaces.")


main()

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 1
Enter numbers separated by spaces: 1 2 3 4 5
Sum: 15.0


**4.2 Exercise on List Manipulation:**
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
    """
    Returns every other element from a list starting from the first element.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list containing every other element.
    """
    return lst[::2]


# Example
numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)

print(result)

[1, 3, 5]


**2. Slice a Sublist:**
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list from start index to end index (inclusive).

    Parameters:
        lst (list): The original list.
        start (int): Starting index.
        end (int): Ending index.

    Returns:
        list: The extracted sublist.
    """
    return lst[start:end+1]


# Example
numbers = [1, 2, 3, 4, 5, 6]
result = get_sublist(numbers, 2, 4)

print(result)

[3, 4, 5]


**3. Reverse a List Using Slicing:**
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
    """
    Returns the reversed version of a list using slicing.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list with elements in reverse order.
    """
    return lst[::-1]


# Example
numbers = [1, 2, 3, 4, 5]
result = reverse_list(numbers)

print(result)

[5, 4, 3, 2, 1]


**4. Remove the First and Last Elements:**
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst):
    """
    Returns a list without the first and last elements.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list with the first and last elements removed.
    """
    return lst[1:-1]


# Example
numbers = [1, 2, 3, 4, 5]
result = remove_first_last(numbers)

print(result)

[2, 3, 4]


**5. Get the First n Elements:**
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst, n):
    """
    Returns the first n elements from a list.
    Parameters:
        lst (list): The input list.
        n (int): Number of elements to extract.
    Returns:
        list: A list containing the first n elements.
    """
    return lst[:n]


# Example
numbers = [1, 2, 3, 4, 5]
result = get_first_n(numbers, 3)

print(result)

[1, 2, 3]


**6. Extract Elements from the End:**
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst, n):
    """
    Returns the last n elements from a list.

    Parameters:
        lst (list): The input list.
        n (int): Number of elements to extract from the end.

    Returns:
        list: A list containing the last n elements.
    """
    return lst[-n:]

numbers = [1, 2, 3, 4, 5]
result = get_last_n(numbers, 2)

print(result)

[4, 5]


**7. Extract Elements in Reverse Order:**
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
    """
    Return every second element from the list starting from
    the second-to-last element and moving backwards.
    """
    return lst[-2::-2]

numbers = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers)

print(result)

[5, 3, 1]


**4.3 Exercise on Nested List:**

**1. Flatten a Nested List:**
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
        lst (list): A nested list.

    Returns:
        list: A flattened list containing all elements.
    """
    result = []

    for sublist in lst:
        for item in sublist:
            result.append(item)

    return result

numbers = [[1, 2], [3, 4], [5]]
print(flatten(numbers))

[1, 2, 3, 4, 5]


**2. Accessing Nested List Elements:**
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):
    """
    Returns an element from a nested list using given indices.
    """
    element = lst

    for index in indices:
        element = element[index]

    return element

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]

print(access_nested_element(lst, indices))

6


**3. Sum of All Elements in a Nested List:**
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
    """
    Returns the sum of all numbers in a nested list.
    """
    total = 0

    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item

    return total
data = [[1, 2], [3, [4, 5]], 6]
print(sum_nested(data))

21


**4. Remove Specific Element from a Nested List:**
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elem):
    """
    Removes all occurrences of elem from a nested list.
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)

    return result

lst = [[1, 2], [3, 2], [4, 5]]
elem = 2

print(remove_element(lst, elem))

[[1], [3], [4, 5]]


**5. Find the Maximum Element in a Nested List:**
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
    """
    Returns the maximum number in a nested list.
    """
    maximum = float('-inf')

    for item in lst:
        if isinstance(item, list):
            value = find_max(item)
            if value > maximum:
                maximum = value
        else:
            if item > maximum:
                maximum = item

    return maximum

data = [[1, 2], [3, [4, 5]], 6]
print(find_max(data))

6


**6. Count Occurrences of an Element in a Nested List:**
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [ ]:
def count_occurrences(lst, elem):
    """
    Counts how many times elem appears in a nested list.
    """
    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1

    return count

lst = [[1, 2], [2, 3], [2, 4]]
elem = 2

print(count_occurrences(lst, elem))

3


**7. Flatten a List of Lists of Lists:**
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into one single list.
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)

    return result

data = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten(data))

[1, 2, 3, 4, 5, 6, 7, 8]


**8. Nested List Average:**
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):
    """
    Returns the average of all numbers in a nested list.
    """
    total = 0
    count = 0

    for item in lst:
        if isinstance(item, list):
            sub_total, sub_count = average_nested(item)
            total += sub_total
            count += sub_count
        else:
            total += item
            count += 1

    return total, count


data = [[1, 2], [3, 4], [5, 6]]

total, count = average_nested(data)
average = total / count

print(average)

G**etting Started with NumPy:**

Short for numerical python. Python library used for numerical computing. widely used in the field that involves heavy data processing such as Data Science, enginnering, AI and ML.

In [ ]:
import numpy as np;
# initialize an all zero array with size 2 X 3:
zeros_arr = np.zeros((2,3))
print(" A zeros array is \n", zeros_arr, "with dimensions", zeros_arr.shape, "\n")

 A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]] with dimensions (2, 3) 



In [ ]:
array = np.array('A')  #this is zero D array
print(array.ndim)
print("array shape", array.shape)
print("array.size - no of elments", array.size)
array = np.array(['A','B','C'])  #this is one D array
print(array.ndim)
print("array shape", array.shape)
print("array.size - no of elments", array.size)
array = np.array([['A','B','C'],['D','E','F']])  #this is two D array
print(array.ndim)
print("array shape", array.shape)
print("array.size - no of elments", array.size)
print("array[0][1] this is chain indexing : ", array[0][1]);
print("array[0,1] this is multidimension indexing : ", array[0,1]);
word = array[0,0] + array[0,1] + array [0,2];
print(word)


0
array shape ()
array.size - no of elments 1
1
array shape (3,)
array.size - no of elments 3
2
array shape (2, 3)
array.size - no of elments 6
array[0][1] this is chain indexing :  B
array[0,1] this is multidimension indexing :  B
ABC


In [ ]:
array = np.array([[1,2,3],[4,5,6], [7,8,9]]);
print("Transpose \n", array.T)

Transpose 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


reshape
The reshape() method in NumPy changes the shape of an array without altering its data, as long as
the total number of elements remains the same before and after reshaping.

In [ ]:
import numpy as np
# Create an array with shape (2, 3)
array = np.array([[1, 2, 3],[4, 5, 6]])

# Reshape to (3, 2), keeping 6 element
reshaped_array = array.reshape(3, 2)
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)


Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


Using in-built function - Arrays with Evenly spaced values:
– arange: The syntax of arange is arange([start,]stop[,step],[,dtype=None])


In [ ]:
import numpy as np
a = np.arange(1, 10)
print(a)
x = range(1, 10)
print(x) # x is an iterator
print(list(x))
# further arange examples:
x = np.arange(10.4)
print(x)
x = np.arange(0.5, 10.4, 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


– linspace: The syntax is linpspace(start,stop,num=50,endpoint=True,retstep=False)

In [ ]:
import numpy as np
# 50 values between 1 and 10:
print(np.linspace(1, 10))
# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))
# excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


Creating or Initializing with Ones, Zeros and Empty:

In [ ]:
import numpy as np
# Create arrays of specified shapes
ones_array = np.ones((2, 3)) # Shape: (2, 3)
zeros_array = np.zeros((3, 2)) # Shape: (3, 2)
empty_array = np.empty((2, 2)) # Shape: (2, 2)
identity_matrix = np.eye(3) # Shape: (3, 3)
print(ones_array,"\n\n", zeros_array, "\n\n", empty_array,"\n\n", identity_matrix)

[[1. 1. 1.]
 [1. 1. 1.]] 

 [[0. 0.]
 [0. 0.]
 [0. 0.]] 

 [[5.54508073e-315 0.00000000e+000]
 [6.62844645e-310 6.62844645e-310]] 

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
# Creating two 3D arrays
arr1 = np.array([[[1], [2]], [[3], [4]]]) # Shape: (2, 2, 1)
arr2 = np.array([[[5], [6]], [[7], [8]]]) # Shape: (2, 2, 1)
# Concatenate along axis 0 (vertical stacking)
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
# Shape of concat_axis0: (4, 2, 1), arr1 is stacked on top of arr2
# Concatenate along axis 1 (horizontal stacking)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
# Shape of concat_axis1: (2, 4, 1), arr1 and arr2 are placed side by side
# Concatenate along axis 2 (depth stacking)
concat_axis2 = np.concatenate((arr1, arr2), axis=2)
# Shape of concat_axis2: (2, 2, 2), arr1 and arr2 are stacked in depth (third
#dimension)
# Displaying the results
print("Concatenation along axis 0 (Vertical stacking):\n", concat_axis0)
print("Shape of concatenated array along axis 0:", concat_axis0.shape)
print("\nConcatenation along axis 1 (Horizontal stacking):\n", concat_axis1)
print("Shape of concatenated array along axis 1:", concat_axis1.shape)
print("\nConcatenation along axis 2 (Depth stacking):\n", concat_axis2)
print("Shape of concatenated array along axis 2:", concat_axis2.shape)

Concatenation along axis 0 (Vertical stacking):
 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]
Shape of concatenated array along axis 0: (4, 2, 1)

Concatenation along axis 1 (Horizontal stacking):
 [[[1]
  [2]
  [5]
  [6]]

 [[3]
  [4]
  [7]
  [8]]]
Shape of concatenated array along axis 1: (2, 4, 1)

Concatenation along axis 2 (Depth stacking):
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Shape of concatenated array along axis 2: (2, 2, 2)


**10 To - Do - NumPy**
Please complete all the problems listed below:
10.1 Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
# 10.1 Basic Vector and Matrix Operations with NumPy
# Import NumPy library (required before using NumPy functions)
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
# (Creates a 2x2 array without initializing entries. Values are random garbage from memory.)

print("1. Empty 2x2 array:\n", empty_array)


# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
# (Creates a 4x2 matrix where every element is 1)

print("\n2. 4x2 array filled with ones:\n", ones_array)


# 3. Return a new array of given shape and type, filled with a specific value
full_array = np.full((3, 3), 7)
# (Creates a 3x3 matrix where every element is the value 7)

print("\n3. Array filled with a specific value (7):\n", full_array)


# 4. Return a new array of zeros with the same shape and type as a given array
zeros_like_array = np.zeros_like(full_array)
# (Creates a new array with same shape as full_array but filled with 0)

print("\n4. Zeros array with same shape as full_array:\n", zeros_like_array)


# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(full_array)
# (Creates a new array with same shape as full_array but filled with 1)

print("\n5. Ones array with same shape as full_array:\n", ones_like_array)


# 6. Convert an existing list into a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
# (Converts the Python list into a NumPy array)

print("\n6. Converted list to NumPy array:\n", numpy_array)

1. Empty 2x2 array:
 [[5.51501781e-315 0.00000000e+000]
 [5.73116149e-322 0.00000000e+000]]

2. 4x2 array filled with ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with a specific value (7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros array with same shape as full_array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

5. Ones array with same shape as full_array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

6. Converted list to NumPy array:
 [1 2 3 4]


**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
# Problem 2: Array Manipulation – Numerical Ranges and Array Indexing

import numpy as np


# 1. Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
# (np.arange(start, end) generates numbers starting from 10 up to 49)

print("1. Array from 10 to 49:\n", arr1)


# 2. Create a 3x3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
# (First create numbers 0–8, then reshape into a 3x3 matrix)

print("\n2. 3x3 matrix from 0 to 8:\n", arr2)


# 3. Create a 3x3 identity matrix
arr3 = np.eye(3)
# (Identity matrix = diagonal values are 1 and everything else is 0)

print("\n3. 3x3 Identity Matrix:\n", arr3)


# 4. Create a random array of size 30 and find the mean
arr4 = np.random.random(30)
# (Creates 30 random numbers between 0 and 1)

mean_value = arr4.mean()
# (Calculates the average of the array)

print("\n4. Random array of size 30:\n", arr4)
print("Mean of the array:", mean_value)


# 5. Create a 10x10 array with random values and find min and max
arr5 = np.random.random((10, 10))
# (Creates a 10x10 matrix filled with random numbers)

min_val = arr5.min()
max_val = arr5.max()

print("\n5. 10x10 random array:\n", arr5)
print("Minimum value:", min_val)
print("Maximum value:", max_val)


# 6. Create a zero array of size 10 and replace 5th element with 1
arr6 = np.zeros(10)
# (Creates an array with 10 zeros)

arr6[4] = 1
# (Index starts from 0, so the 5th element is index 4)

print("\n6. Zero array with 5th element replaced by 1:\n", arr6)


# 7. Reverse an array
arr7 = np.array([1, 2, 0, 0, 4, 0])

reversed_arr = arr7[::-1]
# ([::-1] reverses the order of elements in the array)

print("\n7. Reversed array:\n", reversed_arr)


# 8. Create a 2D array with 1 on border and 0 inside
arr8 = np.ones((5, 5))
# (Start with a 5x5 array filled with 1)

arr8[1:-1, 1:-1] = 0
# (Replace the inner area with 0, keeping borders as 1)

print("\n8. 2D array with border 1 and inside 0:\n", arr8)


# 9. Create an 8x8 checkerboard matrix
arr9 = np.zeros((8, 8), dtype=int)
# (Start with an 8x8 matrix filled with 0)

arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
# (Fill alternate positions with 1 to create checkerboard pattern)

print("\n9. 8x8 Checkerboard pattern:\n", arr9)

1. Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30:
 [0.40694851 0.89437851 0.63993517 0.50615305 0.46189739 0.96525211
 0.65054846 0.00908863 0.86364416 0.0651257  0.8958751  0.07431187
 0.77561742 0.95833372 0.52856341 0.57546529 0.21147235 0.94376832
 0.17182105 0.9195885  0.7356791  0.89581616 0.71691644 0.69120176
 0.43781599 0.98242467 0.72496476 0.18608107 0.71004899 0.64823358]
Mean of the array: 0.6082323746846525

5. 10x10 random array:
 [[0.32326935 0.39001906 0.85924385 0.47734131 0.34205715 0.35422457
  0.77526811 0.46698438 0.5017102  0.79134338]
 [0.60733919 0.29506718 0.17018196 0.27333973 0.39958533 0.96904991
  0.91641501 0.46161026 0.8064112  0.30051109]
 [0.7238613  0.98030674 0.68046291 0.43667616 0.10748022 0.68413314
  0.4

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
# Problem 3: Array Operations

import numpy as np

# Given arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])


# 1. Add the two arrays
add_result = x + y
# (Element-wise addition: corresponding elements of x and y are added)

print("1. Addition of x and y:\n", add_result)


# 2. Subtract the two arrays
subtract_result = x - y
# (Element-wise subtraction: elements of y are subtracted from x)

print("\n2. Subtraction of x and y:\n", subtract_result)


# 3. Multiply the array with any integer
multiply_result = x * 3
# (Each element of x is multiplied by the integer 3)

print("\n3. Multiplying x with integer 3:\n", multiply_result)


# 4. Square of each element of the array
square_result = np.square(x)
# (Squares every element of x)

print("\n4. Square of each element in x:\n", square_result)


# 5. Dot products
dot_vw = np.dot(v, w)
# (Vector dot product: 9*11 + 10*12)

dot_xv = np.dot(x, v)
# (Matrix-vector multiplication)

dot_xy = np.dot(x, y)
# (Matrix multiplication between x and y)

print("\n5. Dot product v · w:", dot_vw)
print("Dot product x · v:\n", dot_xv)
print("Dot product x · y:\n", dot_xy)


# 6. Concatenate x and y along row
concat_xy = np.concatenate((x, y), axis=0)
# (axis=0 means stacking rows vertically)

print("\n6. Concatenate x and y along rows:\n", concat_xy)

# Concatenate v and w along column
concat_vw = np.vstack((v, w)).T
# (First stack vertically then transpose to make them columns)

print("\nConcatenate v and w along columns:\n", concat_vw)


# 7. Concatenate x and v
try_concat = np.concatenate((x, v))
# (This will raise an error because x is 2D and v is 1D.
# NumPy cannot concatenate arrays with different dimensions.)

print("\n7. Attempt to concatenate x and v:\n", try_concat)

1. Addition of x and y:
 [[ 6  8]
 [10 13]]

2. Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

3. Multiplying x with integer 3:
 [[ 3  6]
 [ 9 15]]

4. Square of each element in x:
 [[ 1  4]
 [ 9 25]]

5. Dot product v · w: 219
Dot product x · v:
 [29 77]
Dot product x · y:
 [[19 22]
 [50 58]]

6. Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

**Problem - 4: Matrix Operations:**
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [ ]:
# Problem 3: Array Operations

import numpy as np

# Given arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])


# 1. Add the two arrays
add_result = x + y
# (Element-wise addition: corresponding elements of x and y are added)

print("1. Addition of x and y:\n", add_result)


# 2. Subtract the two arrays
subtract_result = x - y
# (Element-wise subtraction: elements of y are subtracted from x)

print("\n2. Subtraction of x and y:\n", subtract_result)


# 3. Multiply the array with any integer
multiply_result = x * 3
# (Each element of x is multiplied by the integer 3)

print("\n3. Multiplying x with integer 3:\n", multiply_result)


# 4. Square of each element of the array
square_result = np.square(x)
# (Squares every element of x)

print("\n4. Square of each element in x:\n", square_result)


# 5. Dot products
dot_vw = np.dot(v, w)
# (Vector dot product: 9*11 + 10*12)

dot_xv = np.dot(x, v)
# (Matrix-vector multiplication)

dot_xy = np.dot(x, y)
# (Matrix multiplication between x and y)

print("\n5. Dot product v · w:", dot_vw)
print("Dot product x · v:\n", dot_xv)
print("Dot product x · y:\n", dot_xy)


# 6. Concatenate x and y along row
concat_xy = np.concatenate((x, y), axis=0)
# (axis=0 means stacking rows vertically)

print("\n6. Concatenate x and y along rows:\n", concat_xy)

# Concatenate v and w along column
concat_vw = np.vstack((v, w)).T
# (First stack vertically then transpose to make them columns)

print("\nConcatenate v and w along columns:\n", concat_vw)


# 7. Concatenate x and v
try_concat = np.concatenate((x, v))
# (This will raise an error because x is 2D and v is 1D.
# NumPy cannot concatenate arrays with different dimensions.)

print("\n7. Attempt to concatenate x and v:\n", try_concat)

1. Addition of x and y:
 [[ 6  8]
 [10 13]]

2. Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

3. Multiplying x with integer 3:
 [[ 3  6]
 [ 9 15]]

4. Square of each element in x:
 [[ 1  4]
 [ 9 25]]

5. Dot product v · w: 219
Dot product x · v:
 [29 77]
Dot product x · y:
 [[19 22]
 [50 58]]

6. Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

10.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [ ]:
# 10.2 Experiment: How Fast is NumPy?
# Compare performance of Python Lists vs NumPy Arrays

import numpy as np
import time
import random


# ------------------------------------------------------------
# 1. Element-wise Addition
# ------------------------------------------------------------

size = 1_000_000

# Python Lists
list1 = [random.random() for _ in range(size)]
list2 = [random.random() for _ in range(size)]

start = time.time()

result_list_add = [list1[i] + list2[i] for i in range(size)]
# (Manually adding elements one-by-one using list comprehension)

end = time.time()

print("1. Python List Addition Time:", end - start, "seconds")


# NumPy Arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()

result_numpy_add = arr1 + arr2
# (NumPy performs vectorized addition internally in optimized C)

end = time.time()

print("1. NumPy Array Addition Time:", end - start, "seconds")


# ------------------------------------------------------------
# 2. Element-wise Multiplication
# ------------------------------------------------------------

# Python Lists
start = time.time()

result_list_mul = [list1[i] * list2[i] for i in range(size)]
# (Multiplying elements one-by-one)

end = time.time()

print("\n2. Python List Multiplication Time:", end - start, "seconds")


# NumPy Arrays
start = time.time()

result_numpy_mul = arr1 * arr2
# (Vectorized multiplication)

end = time.time()

print("2. NumPy Array Multiplication Time:", end - start, "seconds")


# ------------------------------------------------------------
# 3. Dot Product
# ------------------------------------------------------------

# Python Lists
start = time.time()

dot_list = sum(list1[i] * list2[i] for i in range(size))
# (Multiply each pair then sum all values)

end = time.time()

print("\n3. Python List Dot Product Time:", end - start, "seconds")


# NumPy Arrays
start = time.time()

dot_numpy = np.dot(arr1, arr2)
# (Highly optimized C implementation)

end = time.time()

print("3. NumPy Dot Product Time:", end - start, "seconds")


# ------------------------------------------------------------
# 4. Matrix Multiplication (1000 x 1000)
# ------------------------------------------------------------

matrix_size = 1000

# Python Lists
matrix1 = [[random.random() for _ in range(matrix_size)] for _ in range(matrix_size)]
matrix2 = [[random.random() for _ in range(matrix_size)] for _ in range(matrix_size)]

start = time.time()

result_matrix = [[0]*matrix_size for _ in range(matrix_size)]

for i in range(matrix_size):
    for j in range(matrix_size):
        for k in range(matrix_size):
            result_matrix[i][j] += matrix1[i][k] * matrix2[k][j]
# (Classic triple-loop matrix multiplication)

end = time.time()

print("\n4. Python List Matrix Multiplication Time:", end - start, "seconds")


# NumPy Arrays
np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)

start = time.time()

result_numpy_matrix = np.dot(np_matrix1, np_matrix2)
# (Uses highly optimized BLAS/LAPACK operations)

end = time.time()

print("4. NumPy Matrix Multiplication Time:", end - start, "seconds")

1. Python List Addition Time: 0.11707258224487305 seconds
1. NumPy Array Addition Time: 0.003965139389038086 seconds

2. Python List Multiplication Time: 0.19008803367614746 seconds
2. NumPy Array Multiplication Time: 0.004528999328613281 seconds

3. Python List Dot Product Time: 0.08491921424865723 seconds
3. NumPy Dot Product Time: 0.0015461444854736328 seconds

4. Python List Matrix Multiplication Time: 356.6695730686188 seconds
4. NumPy Matrix Multiplication Time: 0.06980562210083008 seconds
